backend:
  name: github
  repo: Fengyue-Yj/wuxian
  branch: master


media_folder: "public/images"
public_folder: "/wuxian/images"

collections:
  - name: "essays"
    label: "随笔 (Essays)"
    folder: "content/essays"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "摘要", name: "excerpt", widget: "text", required: false}
      - {label: "正文", name: "body", widget: "markdown"}
